version: '2'

services:
  postgres:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    container_name: postgres

  redis:
    image: redis:2.8
    container_name: redis
    ports:
      - "6379:6379"
